# Generated by Django 5.2.4 on 2025-10-26 01:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'association")),
                ('type_association', models.CharField(choices=[('sante_mentale', 'Santé Mentale'), ('aide_sociale', 'Aide Sociale'), ('urgence', 'Urgence'), ('benevoles', 'Bénévoles'), ('autre', 'Autre')], default='sante_mentale', max_length=50, verbose_name="Type d'association")),
                ('zone_intervention', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('kaolack', 'Kaolack'), ('saint_louis', 'Saint-Louis'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('autre', 'Autre')], max_length=50, verbose_name="Zone d'intervention")),
                ('description', models.TextField(verbose_name="Description de l'association")),
                ('contact_telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone de contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='associations/logos/', verbose_name='Logo')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('est_verifiee', models.BooleanField(default=False, verbose_name='Association vérifiée')),
                ('est_active', models.BooleanField(default=True, verbose_name='Association active')),
                ('compte_mobile_money', models.CharField(blank=True, max_length=20, null=True, verbose_name='Compte Mobile Money')),
                ('compte_paypal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email PayPal')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur responsable')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BesoinUrgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_besoin', models.CharField(choices=[('argent', 'Argent'), ('medicament', 'Médicament'), ('vetement', 'Vêtement'), ('nourriture', 'Nourriture'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=50, verbose_name='Type de besoin')),
                ('description', models.TextField(verbose_name='Description du besoin')),
                ('quantite_demandee', models.CharField(max_length=100, verbose_name='Quantité demandée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('est_urgent', models.BooleanField(default=True, verbose_name='Besoin urgent')),
                ('est_satisfait', models.BooleanField(default=False, verbose_name='Besoin satisfait')),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant estimé (FCFA)')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins_urgents', to='associations.association', verbose_name='Association')),
            ],
            options={
                'verbose_name': 'Besoin urgent',
                'verbose_name_plural': 'Besoins urgents',
                'ordering': ['-date_creation'],
            },
        ),
    ]
