# Generated by Django 5.2.4 on 2025-10-26 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255, verbose_name='Lieu du signalement')),
                ('description', models.TextField(verbose_name='Description de la situation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/photos/', verbose_name='Photo (optionnelle)')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Date du signalement')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('pris_en_charge', 'Pris en charge'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('niveau_urgence', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name="Niveau d'urgence")),
                ('contact_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de contact')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('adresse_complete', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateTimeField(auto_now_add=True, verbose_name="Date d'intervention")),
                ('commentaire', models.TextField(verbose_name="Commentaire sur l'intervention")),
                ('statut_intervention', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name="Statut de l'intervention")),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.association', verbose_name='Association')),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='signalements.signalement', verbose_name='Signalement')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_intervention'],
            },
        ),
    ]
