# Generated by Django 5.2.4 on 2025-10-26 01:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
        ('signalements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la campagne')),
                ('description', models.TextField(verbose_name='Description')),
                ('objectif_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Objectif de montant (FCFA)')),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant collecté (FCFA)')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='active', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campagnes/', verbose_name='Image')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.association', verbose_name='Association')),
            ],
            options={
                'verbose_name': 'Campagne de don',
                'verbose_name_plural': 'Campagnes de dons',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_don', models.CharField(choices=[('argent', 'Argent'), ('medicament', 'Médicament'), ('vetement', 'Vêtement'), ('nourriture', 'Nourriture'), ('autre', 'Autre')], max_length=50, verbose_name='Type de don')),
                ('description', models.TextField(verbose_name='Description du don')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (FCFA)')),
                ('quantite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut du don')),
                ('commentaire_donateur', models.TextField(blank=True, null=True, verbose_name='Commentaire du donateur')),
                ('commentaire_association', models.TextField(blank=True, null=True, verbose_name="Commentaire de l'association")),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de contact')),
                ('adresse_remise', models.TextField(blank=True, null=True, verbose_name='Adresse de remise')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='associations.association', verbose_name='Association destinataire')),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Donateur')),
                ('signalement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalements.signalement', verbose_name='Signalement lié')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('date_changement', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='dons.don', verbose_name='Don')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de don',
                'verbose_name_plural': 'Historiques de dons',
                'ordering': ['-date_changement'],
            },
        ),
    ]
